services:
  gemini-balance:
    build: .
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./logs:/app/backend/logs # 调整日志路径
    # 与Open Webui 共享网络，如果不需要，可删除shared_net
    networks:
      - shared_net
    environment:
      - APP_ENV=production
      # 根据需要配置代理环境，如不需要，可删除v2rayA
      - HTTP_PROXY=http://v2raya:20170
      - HTTPS_PROXY=http://v2raya:20170
      - REDIS_URL=redis://gemini-balance-redis:6379/0
    depends_on:
      gemini-balance-redis:
        condition: service_healthy
      v2raya:
        condition: service_started

  gemini-balance-redis:
    image: redis:alpine
    container_name: gemini-balance-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_net

  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    # 与Open Webui 共享网络，如果不需要，可删除shared_net
    networks:
      - shared_net
    restart: always
    ports:
      - "2017:2017"
      - "20170-20172:20170-20172"
    environment:
      - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
    volumes:
      - v2raya_config:/etc/v2raya

volumes:
  redis_data:
  v2raya_config:

# 与Open Webui 共享网络，如果不需要，可删除shared_net
networks:
  shared_net:
    external: true
    name: gemini-balance-open-webui
